#!/usr/bin/env python3
"""Generate PngRowDecoderFixtures.h: small PNGs with known raw rows.

Each image cycles the five PNG filter types row by row and splits its zlib
stream across several IDAT chunks, so the decoder's unfiltering and chunk
walking are checked against bytes this script chose, not another decoder.

Run from the repo root: python3 test/png_row_decoder/make_fixtures.py
"""
import pathlib
import random
import struct
import zlib

OUT = pathlib.Path(__file__).with_name("PngRowDecoderFixtures.h")
CHANNELS = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}


def chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)


def paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    return a if pa <= pb and pa <= pc else (b if pb <= pc else c)


def filter_row(kind, row, prev, bpp):
    out = bytearray(len(row))
    for i, x in enumerate(row):
        a = row[i - bpp] if i >= bpp else 0
        b = prev[i]
        c = prev[i - bpp] if i >= bpp else 0
        pred = [0, a, b, (a + b) // 2, paeth(a, b, c)][kind]
        out[i] = (x - pred) & 0xFF
    return bytes([kind]) + bytes(out)


def make_png(width, height, color, depth, rng, extra_chunks=(), idat_split=7):
    bits = CHANNELS[color] * depth
    row_bytes = (width * bits + 7) // 8
    bpp = max(1, bits // 8)
    rows = []
    for y in range(height):
        row = bytearray(rng.randrange(256) for _ in range(row_bytes))
        pad = row_bytes * 8 - width * bits
        if pad:
            row[-1] &= (0xFF << pad) & 0xFF  # unused low bits stay zero
        rows.append(bytes(row))
    raw = b""
    prev = bytes(row_bytes)
    for y, row in enumerate(rows):
        raw += filter_row(y % 5, row, prev, bpp)
        prev = row
    z = zlib.compress(raw, 9)
    idats = b"".join(chunk(b"IDAT", z[i : i + idat_split]) for i in range(0, len(z), idat_split))
    ihdr = struct.pack(">IIBBBBB", width, height, depth, color, 0, 0, 0)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + b"".join(extra_chunks) + idats + chunk(b"IEND", b"")
    return png, rows


def main():
    rng = random.Random(20261007)
    cases = []
    for color, depths in ((0, (1, 2, 4, 8, 16)), (2, (8, 16)), (3, (1, 2, 4, 8)), (4, (8, 16)), (6, (8, 16))):
        for depth in depths:
            extra = []
            note = ""
            if color == 3:
                n = 1 << depth
                extra.append(chunk(b"PLTE", bytes(rng.randrange(256) for _ in range(n * 3))))
            cases.append((f"c{color}_d{depth}", 13, 7, color, depth, extra))
    # tRNS variants: palette alpha, gray and RGB color keys, plus an ancillary chunk to skip.
    cases.append(("palette_trns", 9, 5, 3, 4,
                  [chunk(b"PLTE", bytes(range(48))), chunk(b"tEXt", b"Comment\x00skip me"),
                   chunk(b"tRNS", bytes([0, 64, 128, 255, 7]))]))
    cases.append(("gray_trns", 9, 5, 0, 8, [chunk(b"tRNS", bytes([0, 0x5A]))]))
    cases.append(("rgb_trns", 9, 5, 2, 8, [chunk(b"tRNS", bytes([0, 0x11, 0, 0x22, 0, 0x33]))]))
    cases.append(("wide_rgba", 300, 4, 6, 8, []))

    lines = ["// Generated by make_fixtures.py. Do not edit.", "#pragma once", "#include <cstddef>", "#include <cstdint>",
             "", "struct PngFixture {", "  const char* name;", "  const uint8_t* png;", "  size_t pngSize;",
             "  const uint8_t* rows;", "  uint32_t width, height;", "  uint8_t colorType, bitDepth;", "};", ""]
    entries = []
    for name, w, h, color, depth, extra in cases:
        png, rows = make_png(w, h, color, depth, rng, extra)
        flat = b"".join(rows)
        lines.append(f"static const uint8_t {name}_png[] = {{" + ",".join(str(b) for b in png) + "};")
        lines.append(f"static const uint8_t {name}_rows[] = {{" + ",".join(str(b) for b in flat) + "};")
        entries.append(f'    {{"{name}", {name}_png, sizeof({name}_png), {name}_rows, {w}, {h}, {color}, {depth}}},')
    lines.append("static const PngFixture kPngFixtures[] = {")
    lines += entries
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(cases)} images)")


if __name__ == "__main__":
    main()
