#pragma once

#include "Icon.h"

// Generated by libs/assets/Icons/tools/gen_icons.py from Lucide SVGs. Do not edit.
// Sizes: 10px. Icons: 1.

// check  (lucide: check)
static const uint8_t icon_check_10_bits[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0x7F, 0xFC, 0xFF, 0xB9, 0xFF,
                                             0x93, 0xFF, 0xC7, 0xFF, 0xEF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
static const freeink::Icon icon_check_10 = {10, 10, 4, icon_check_10_bits};
